services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "50051:50051"
      - "27017:27017"
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
